default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - commit
  - push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.290
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or:
          - python
          - pyi
          - jupyter
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.0.0
    hooks:
      - id: nb-clean
  - repo: https://github.com/omnilib/ufmt
    rev: v2.2.0
    hooks:
      - id: ufmt
        additional_dependencies:
          - black ~= 23.9
          - usort ~= 1.0
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black-jupyter
        language_version: python3.10
        types_or:
          - jupyter
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.8.2
    hooks:
      - id: commitizen
