default_install_hook_types:
  # Default stage
  - pre-commit
  - pre-push
  # Needed for uv-sync
  - post-checkout
  - post-merge
  - post-rewrite

default_stages:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.15
    hooks:
      - id: uv-lock
      - id: uv-sync
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        # Optionally add plugins
        additional_dependencies:
          - mdformat-gfm
          - mdformat-ruff
          - mdformat-frontmatter
          - mdformat-footnote
          - mdformat-gfm-alerts
        exclude: ^CHANGELOG.md$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        exclude: ^CHANGELOG.md$
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
      - id: pyright
